### ISSUE TITLE
При активации "Создать источник для сериалов lostfilm..."

### ISSUE THREAD

**Issue by maltsevvv** [Tommixoft/plugin.video.lostfilm.tv#1]
16:05:57.482 T:139874866427648   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'xbmcswift2.urls.NotFoundException'>
                                            Error Contents: No matching view found for /create_source
                                            Traceback (most recent call last):
                                              File "/home/kodi/.kodi/addons/plugin.video.lostfilm.tv/addon.py", line 31, in <module>
                                                launch()
                                              File "/home/kodi/.kodi/addons/plugin.video.lostfilm.tv/addon.py", line 17, in launch
                                                plugin.run()
                                              File "/home/kodi/.kodi/addons/plugin.video.lostfilm.tv/resources/lib/vendor/xbmcswift2/plugin.py", line 342, in run
                                                items = self._dispatch(self.request.path)
                                              File "/home/kodi/.kodi/addons/plugin.video.lostfilm.tv/resources/lib/vendor/xbmcswift2/plugin.py", line 314, in _dispatch
                                                raise NotFoundException('No matching view found for %s' % path)
                                            NotFoundException: No matching view found for /create_source
                                            -->End of Python script error report<--

**Comment by Tommixoft** [comment]
This function is NOT available yet. You can not create KODI source unfortunately..
